In [2]:
import torch
import numpy as np
import pandas as pd

In [3]:
torch.randperm(10)

tensor([8, 1, 5, 0, 2, 6, 3, 7, 4, 9])

In [4]:
torch.arange(10, 40, 2)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [5]:
torch.arange(0, 10, 0.5)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])

In [6]:
torch.arange(0, 10, 1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
d = torch.randn(4, 5)
d

tensor([[-0.2564,  0.3414,  1.2003, -0.9074,  0.4071],
        [ 2.9279,  0.8123,  1.0742,  0.4350, -0.0795],
        [ 1.0676,  1.0906,  1.5639,  0.6868, -1.3784],
        [ 1.4104, -0.3007,  1.2990, -0.7705,  0.3513]])

In [9]:
torch.argmin(d)

tensor(14)

In [11]:
torch.argmin(d, dim=1)

tensor([3, 4, 4, 3])

In [12]:
torch.argmin(d, dim=0)

tensor([0, 3, 1, 0, 2])

In [13]:
torch.argmax(d)

tensor(5)

torch.argmax(tensor_d, dim=n)：
获取tensor_d第n个dim的最大值
torch.argmin(tensor_d, dim=n)：
获取tensor_d第n个dim的最小值


torch.zeros(4, 5): create a 2d tensor filled with values as 0
torch.zeros(10):create a 1d tensor filled with values as 0

In [14]:
torch.zeros(4, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [15]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


torch.cat((tensor_x, tensor_x)):concatenate two tensors, default over column
torch.cat((tensor_x, tensor_x), 0)可以理解为两个矩阵上下排列
torch.cat((tensor_x, tensor_x), 1)可以理解为两个矩阵左右并排

In [18]:
x = torch.randn(4, 5)
x

tensor([[ 2.3398,  0.3509, -0.6197, -0.1755,  0.3048],
        [-0.6877,  1.4308,  1.7688, -0.1704,  0.6963],
        [ 0.8112,  1.4719, -1.2023, -0.6768,  0.2971],
        [ 0.1268,  0.7133,  0.8222, -1.2310, -0.4410]])

In [19]:
torch.cat((x, x))

tensor([[ 2.3398,  0.3509, -0.6197, -0.1755,  0.3048],
        [-0.6877,  1.4308,  1.7688, -0.1704,  0.6963],
        [ 0.8112,  1.4719, -1.2023, -0.6768,  0.2971],
        [ 0.1268,  0.7133,  0.8222, -1.2310, -0.4410],
        [ 2.3398,  0.3509, -0.6197, -0.1755,  0.3048],
        [-0.6877,  1.4308,  1.7688, -0.1704,  0.6963],
        [ 0.8112,  1.4719, -1.2023, -0.6768,  0.2971],
        [ 0.1268,  0.7133,  0.8222, -1.2310, -0.4410]])

In [20]:
torch.cat((x, x), 0)

tensor([[ 2.3398,  0.3509, -0.6197, -0.1755,  0.3048],
        [-0.6877,  1.4308,  1.7688, -0.1704,  0.6963],
        [ 0.8112,  1.4719, -1.2023, -0.6768,  0.2971],
        [ 0.1268,  0.7133,  0.8222, -1.2310, -0.4410],
        [ 2.3398,  0.3509, -0.6197, -0.1755,  0.3048],
        [-0.6877,  1.4308,  1.7688, -0.1704,  0.6963],
        [ 0.8112,  1.4719, -1.2023, -0.6768,  0.2971],
        [ 0.1268,  0.7133,  0.8222, -1.2310, -0.4410]])

In [21]:
torch.cat((x, x), 1)

tensor([[ 2.3398,  0.3509, -0.6197, -0.1755,  0.3048,  2.3398,  0.3509, -0.6197,
         -0.1755,  0.3048],
        [-0.6877,  1.4308,  1.7688, -0.1704,  0.6963, -0.6877,  1.4308,  1.7688,
         -0.1704,  0.6963],
        [ 0.8112,  1.4719, -1.2023, -0.6768,  0.2971,  0.8112,  1.4719, -1.2023,
         -0.6768,  0.2971],
        [ 0.1268,  0.7133,  0.8222, -1.2310, -0.4410,  0.1268,  0.7133,  0.8222,
         -1.2310, -0.4410]])

torch.chunk(tensor_a, n, dim):将tensor a在维度dim上分为n个chunk

In [22]:
a = torch.randn(4, 4)
a

tensor([[ 0.9902, -1.2278,  1.0631,  0.1930],
        [ 0.7021,  0.7447,  1.6477,  0.1638],
        [-0.9053,  0.0170, -0.5844,  0.5770],
        [ 0.6396,  1.1039,  0.0403,  0.1938]])

In [23]:
torch.chunk(a, 2)

(tensor([[ 0.9902, -1.2278,  1.0631,  0.1930],
         [ 0.7021,  0.7447,  1.6477,  0.1638]]),
 tensor([[-0.9053,  0.0170, -0.5844,  0.5770],
         [ 0.6396,  1.1039,  0.0403,  0.1938]]))

In [24]:
torch.chunk(a, 2, 1)

(tensor([[ 0.9902, -1.2278],
         [ 0.7021,  0.7447],
         [-0.9053,  0.0170],
         [ 0.6396,  1.1039]]),
 tensor([[ 1.0631,  0.1930],
         [ 1.6477,  0.1638],
         [-0.5844,  0.5770],
         [ 0.0403,  0.1938]]))

torch.index_select(tensor_x, dim, indices):从dim维选择tensor a 的indices chunk

In [25]:
indices = torch.LongTensor([0, 2])
indices

tensor([0, 2])

In [26]:
a = torch.randn(4, 4)
a

tensor([[-0.9066, -0.0897, -1.4948,  1.5836],
        [ 1.8722,  0.4151,  0.2181,  0.3334],
        [-0.0035, -0.5193, -0.5201, -0.6211],
        [-0.2464, -0.9893, -1.3760, -0.8599]])

In [27]:
torch.index_select(a, 0, indices)

tensor([[-0.9066, -0.0897, -1.4948,  1.5836],
        [-0.0035, -0.5193, -0.5201, -0.6211]])

In [28]:
torch.index_select(a, 1, indices)

tensor([[-0.9066, -1.4948],
        [ 1.8722,  0.2181],
        [-0.0035, -0.5201],
        [-0.2464, -1.3760]])

In [ ]:
torch.nonzero(tensor_a):找到tensor a中非零元的位置

In [29]:
torch.nonzero(torch.tensor([10, 00, 23, 0, 0.0]))

..\torch\csrc\utils\python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple)


tensor([[0],
        [2]])

In [ ]:
torch.split(tensor_a, n):将tensor a 分割为多个tensor，每个tensor分割包含n个元素

In [30]:
torch.split(torch.tensor([12, 21, 34, 32, 45, 54, 56, 65]), 2)

(tensor([12, 21]), tensor([34, 32]), tensor([45, 54]), tensor([56, 65]))

In [31]:
torch.split(torch.tensor([12, 21, 34, 32, 45, 54, 56, 65]), 3)

(tensor([12, 21, 34]), tensor([32, 45, 54]), tensor([56, 65]))

tensor_x.t()
tensor_x.transpose(1, 0):将tensor x转置

In [32]:
x

tensor([[ 2.3398,  0.3509, -0.6197, -0.1755,  0.3048],
        [-0.6877,  1.4308,  1.7688, -0.1704,  0.6963],
        [ 0.8112,  1.4719, -1.2023, -0.6768,  0.2971],
        [ 0.1268,  0.7133,  0.8222, -1.2310, -0.4410]])

In [33]:
x.t()

tensor([[ 2.3398, -0.6877,  0.8112,  0.1268],
        [ 0.3509,  1.4308,  1.4719,  0.7133],
        [-0.6197,  1.7688, -1.2023,  0.8222],
        [-0.1755, -0.1704, -0.6768, -1.2310],
        [ 0.3048,  0.6963,  0.2971, -0.4410]])

In [34]:
x.transpose(1, 0)

tensor([[ 2.3398, -0.6877,  0.8112,  0.1268],
        [ 0.3509,  1.4308,  1.4719,  0.7133],
        [-0.6197,  1.7688, -1.2023,  0.8222],
        [-0.1755, -0.1704, -0.6768, -1.2310],
        [ 0.3048,  0.6963,  0.2971, -0.4410]])

torch.unbind(tensor_x, dim):将tensor按照维度dim分解，将高维分解为低维

In [35]:
x

tensor([[ 2.3398,  0.3509, -0.6197, -0.1755,  0.3048],
        [-0.6877,  1.4308,  1.7688, -0.1704,  0.6963],
        [ 0.8112,  1.4719, -1.2023, -0.6768,  0.2971],
        [ 0.1268,  0.7133,  0.8222, -1.2310, -0.4410]])

In [36]:
torch.unbind(x, 1)

(tensor([ 2.3398, -0.6877,  0.8112,  0.1268]),
 tensor([0.3509, 1.4308, 1.4719, 0.7133]),
 tensor([-0.6197,  1.7688, -1.2023,  0.8222]),
 tensor([-0.1755, -0.1704, -0.6768, -1.2310]),
 tensor([ 0.3048,  0.6963,  0.2971, -0.4410]))

In [37]:
torch.unbind(x, 0)

(tensor([ 2.3398,  0.3509, -0.6197, -0.1755,  0.3048]),
 tensor([-0.6877,  1.4308,  1.7688, -0.1704,  0.6963]),
 tensor([ 0.8112,  1.4719, -1.2023, -0.6768,  0.2971]),
 tensor([ 0.1268,  0.7133,  0.8222, -1.2310, -0.4410]))

In [38]:
torch.unbind(x[0], 0)

(tensor(2.3398),
 tensor(0.3509),
 tensor(-0.6197),
 tensor(-0.1755),
 tensor(0.3048))

In [39]:
torch.unbind(x[0], 1)  # 出错是因为x[0]只有一个维度，标记为0
# 另外，tensor 1d 和 numpy 相似是一个行向量

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

torch.add(tensor_x, tensor_y):将两个tensor按照元素相加

In [40]:
x

tensor([[ 2.3398,  0.3509, -0.6197, -0.1755,  0.3048],
        [-0.6877,  1.4308,  1.7688, -0.1704,  0.6963],
        [ 0.8112,  1.4719, -1.2023, -0.6768,  0.2971],
        [ 0.1268,  0.7133,  0.8222, -1.2310, -0.4410]])

In [41]:
torch.add(x, 10)

tensor([[12.3398, 10.3509,  9.3803,  9.8245, 10.3048],
        [ 9.3123, 11.4308, 11.7688,  9.8296, 10.6963],
        [10.8112, 11.4719,  8.7977,  9.3232, 10.2971],
        [10.1268, 10.7133, 10.8222,  8.7690,  9.5590]])

In [42]:
torch.add(x, x)

tensor([[ 4.6797,  0.7017, -1.2394, -0.3510,  0.6096],
        [-1.3754,  2.8615,  3.5376, -0.3408,  1.3927],
        [ 1.6224,  2.9439, -2.4047, -1.3536,  0.5941],
        [ 0.2537,  1.4267,  1.6445, -2.4619, -0.8820]])

tensor.mul(x, y): 将x和y相乘，如果一个是标量一个是tensor那么类似标量乘以矩阵，如果两个都是tensor，那么是point-wise

In [43]:
torch.mul(x, 2)

tensor([[ 4.6797,  0.7017, -1.2394, -0.3510,  0.6096],
        [-1.3754,  2.8615,  3.5376, -0.3408,  1.3927],
        [ 1.6224,  2.9439, -2.4047, -1.3536,  0.5941],
        [ 0.2537,  1.4267,  1.6445, -2.4619, -0.8820]])

In [44]:
torch.mul(x, x)

tensor([[5.4748, 0.1231, 0.3841, 0.0308, 0.0929],
        [0.4729, 2.0471, 3.1287, 0.0290, 0.4849],
        [0.6581, 2.1666, 1.4456, 0.4580, 0.0882],
        [0.0161, 0.5088, 0.6761, 1.5153, 0.1945]])

torch.ceil(x):将x中的每个元素都向上取整
torch.floor(x):向下取整

In [46]:
torch.manual_seed(123)
torch.ceil(torch.randn(5, 5))

tensor([[ 1., -0., -0., -0.,  1.],
        [ 1., -0., -0.,  1., -0.],
        [ 1., -1.,  2., -0.,  2.],
        [-1., -1., -1., -0.,  1.],
        [ 1.,  1.,  2., -0.,  1.]])

In [47]:
torch.manual_seed(1)
x = torch.randn(5, 5)
x

tensor([[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
        [-0.6092, -0.9798, -1.6091, -0.7121,  1.1712],
        [ 1.7674, -0.0954,  0.1394, -1.5785, -0.3206],
        [-0.2993,  1.8793,  0.3357,  0.2753,  1.7163],
        [-0.0561,  0.9107, -1.3924,  2.6891, -0.1110]])

In [49]:
torch.ceil(x)

tensor([[-1., -0., -0., -1., -0.],
        [-0., -0., -1., -0.,  2.],
        [ 2., -0.,  1., -1., -0.],
        [-0.,  2.,  1.,  1.,  2.],
        [-0.,  1., -1.,  3., -0.]])

In [50]:
torch.floor(x)

tensor([[-2., -1., -1., -2., -1.],
        [-1., -1., -2., -1.,  1.],
        [ 1., -1.,  0., -2., -1.],
        [-1.,  1.,  0.,  0.,  1.],
        [-1.,  0., -2.,  2., -1.]])

torch.exp(x):对每个x中的元素做取指数运算

In [51]:
x = torch.randn(2, 2)
x

tensor([[-0.1103,  0.2913],
        [ 0.5848,  0.2149]])

In [52]:
torch.exp(x)

tensor([[0.8956, 1.3382],
        [1.7946, 1.2398]])

In [53]:
np.exp(x)

tensor([[0.8956, 1.3382],
        [1.7946, 1.2398]])

torch.frac(x):获取x中每个元素的小数部分

In [55]:
x = torch.add(x, 10)
x

tensor([[ 9.8897, 10.2913],
        [10.5848, 10.2149]])

In [56]:
torch.frac(x)

tensor([[0.8897, 0.2913],
        [0.5848, 0.2149]])

torch.log(x):对x的每个元素取对数，如果这个元素小于等于0，那么得到的值为nan
torch.pow(x, n):对x的每个元素计算n次方
torch.sqrt(x):计算每个元素的平方根
torch.sigmoid(x):对每个元素应用sigmoid函数

In [57]:
x = torch.randn(2, 2)
x

tensor([[-0.4090, -0.1663],
        [ 0.6696,  0.1177]])

In [58]:
torch.log(x)

tensor([[    nan,     nan],
        [-0.4011, -2.1397]])

In [59]:
torch.pow(x, 2)

tensor([[0.1673, 0.0277],
        [0.4484, 0.0139]])

总结：这部分学习pytorch中tensor的创建、连结、分割、去除维度、选择、以及常用的+， -， *， /，log， exp 等基本函数操作