这一部分主要学习一些pytorch中常用的关于随机变量的操作。
torch.distributions module 包含了一些概率分布和函数。概率分布有二项分布、伯努利分布、beta分布、指数分布、正态分布、泊松分布、多伯努利分布（分类分布）。

In [1]:
import torch

In [2]:
torch.manual_seed(123)

In [3]:
torch.randn(4, 4)

tensor([[ 0.3374, -0.1778, -0.3035, -0.5880],
        [ 0.3486,  0.6603, -0.2196, -0.3792],
        [ 0.7671, -1.1925,  0.6984, -1.4097],
        [ 0.1794,  1.8951,  0.4954,  0.2692]])

torch.Tensor(4, 4).uniform_(0, 1):生成4 * 4 的[0, 1]之间的均匀分布

In [4]:
torch.Tensor(4, 4).uniform_(0, 1)

tensor([[0.1186, 0.8274, 0.3821, 0.6605],
        [0.8536, 0.5932, 0.6367, 0.9826],
        [0.2745, 0.6584, 0.2775, 0.8573],
        [0.8993, 0.0390, 0.9268, 0.7388]])

torch.bernoulli(tensor_x):根据tensor x的概率生成x维度的Bernoulli分布数

In [6]:
torch.bernoulli(torch.Tensor(4, 4).uniform_(0, 1))

tensor([[0., 1., 0., 0.],
        [0., 1., 1., 0.],
        [0., 0., 1., 0.],
        [1., 0., 1., 1.]])

In [15]:
torch.bernoulli(torch.tensor([0.9, 0.9, 0.9, 0.9]))

tensor([1., 1., 1., 1.])

torch.multinomial(tensor_x, n)：从tensor x中选择n个出来

In [16]:
torch.multinomial(torch.rand(4, 4), 3)

tensor([[3, 2, 1],
        [2, 0, 1],
        [0, 1, 3],
        [2, 0, 1]])

In [17]:
x = torch.rand(4, 4)

In [18]:
x

tensor([[0.5757, 0.2785, 0.1946, 0.5382],
        [0.1291, 0.1242, 0.1746, 0.3302],
        [0.5370, 0.8443, 0.6937, 0.8831],
        [0.1861, 0.5422, 0.0556, 0.7868]])

In [19]:
torch.multinomial(x, 3)

tensor([[3, 0, 1],
        [3, 2, 1],
        [3, 1, 0],
        [2, 3, 1]])

In [26]:
torch.multinomial(x, 5, replacement=True)

tensor([[1, 3, 3, 1, 3],
        [3, 2, 0, 3, 1],
        [0, 3, 1, 3, 1],
        [3, 1, 3, 1, 3]])

In [33]:
x = torch.tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
        18., 19.])
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19.])

In [35]:
torch.multinomial(x, 12, replacement=True)

tensor([13, 13, 14, 13, 19, 19, 13, 12, 13, 10, 13, 16])

torch.normal(mean=tensor_mean, std=tensor_std):从均值向量和方差向量中生成正态分布

In [40]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([1.8049, 1.7203, 2.2634, 3.8945, 4.5814, 6.7613, 7.9723, 8.4709, 8.9869,
        9.9572])

In [41]:
torch.normal(mean=0.5, std=torch.arange(1., 6.))

tensor([ 0.7537,  1.9675,  3.9164,  2.7065, -2.5934])

Pytorch中变量是计算图中的节点，保存了变量的值和梯度。因为要计算变量的梯度，计算图中的任务的顺序序列就显得非常重要.
torch中变量创建Variable(tensor_x, requires_grad=True), 参数为True表示需要对变量求导，变量节点将会保存梯度

In [42]:
from torch.autograd import Variable

In [43]:
Variable(torch.ones(2, 2), requires_grad=True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [44]:
a, b = 12, 23
x1 = Variable(torch.randn(a, b), requires_grad=True)
x2 = Variable(torch.randn(a, b), requires_grad=True)
x3 = Variable(torch.randn(a, b), requires_grad=True)

In [46]:
c = x1 * x2
d = a + x3
e = torch.sum(d)
e.backward()
print(e)

tensor(3312.6350, grad_fn=<SumBackward0>)


In [47]:
x1

tensor([[-0.2115, -0.2708, -0.0830, -0.2453, -0.9124, -1.4065,  0.3187,  0.8451,
          0.0040,  0.3480,  1.7276, -2.5230,  0.2561,  1.0097, -0.4543,  0.7966,
          1.4440, -1.5852, -0.4536,  0.2158, -0.4391, -0.2247, -1.4327],
        [ 0.2142,  1.1908, -1.8039,  0.4719,  0.0814, -1.2219, -0.4522, -0.6456,
         -0.4094,  0.8423, -2.4813,  0.1389,  2.2357,  1.5243,  0.1121,  1.0119,
         -0.4792, -0.0425,  0.3271, -0.4837, -1.0132,  1.3344, -0.3179],
        [ 0.4384,  0.5438, -0.7368,  0.2564,  0.1585,  0.1202,  0.4888, -0.0180,
          0.8637,  0.2074,  0.4073,  0.0080,  0.1839, -0.1475,  0.0373,  0.7058,
          0.2657, -1.7271, -1.8981, -1.2470, -0.7558, -0.1980, -0.4630],
        [-1.5418, -1.1920, -0.1908, -0.2911, -0.1204, -0.0221, -0.9555,  1.1367,
         -0.3091, -0.0160, -0.7645, -0.5497,  0.4804, -0.4132, -0.8006, -2.0753,
          0.7684, -0.7082,  0.7290, -0.3591,  0.0168, -0.1568,  1.3547],
        [ 0.5045, -3.2272,  1.3297,  0.6955,  0.5150, -0.836

In [48]:
d

tensor([[11.5699, 12.9339, 11.5278, 12.8510, 12.1990, 12.7787, 11.3002, 12.0387,
         10.1687, 11.9483, 11.9655, 11.3536, 11.6419, 11.5160, 11.7287, 11.9226,
         12.5229, 12.1553, 12.5247, 11.5083, 12.5103, 11.2270, 11.6588],
        [13.4254, 11.9305, 11.8371, 10.6163, 12.6189,  8.9515, 10.9550, 12.8434,
         13.8587,  8.0701, 12.3435, 10.8833, 11.2296, 12.1609, 11.2756, 12.0543,
         11.0335, 12.6363, 11.9305, 11.1918, 11.9934, 11.6410, 12.3171],
        [11.1471, 10.5291, 11.6269, 12.2299, 13.6853, 11.6928, 11.9113, 12.1228,
         12.8227, 10.8557, 10.9068, 12.5156, 13.0474, 12.4452, 13.5324, 12.0284,
         11.0375, 11.6038, 10.9388, 13.3935, 11.4406, 11.6117, 11.6650],
        [11.1499, 10.1822, 12.7297, 13.2289, 11.1263, 12.6285, 12.7906, 11.5853,
         14.0388, 11.9810, 11.3063, 12.4173, 13.0526, 11.5843, 11.9984, 11.4970,
         12.7011, 13.8257, 12.0427, 11.6913, 13.4557, 11.4317, 12.9882],
        [13.5823, 10.8341, 12.1383, 11.0199, 13.0355, 12.321

torch.mean(tensor_x, dim=n):按照第n维计算tensor x的均值
torch.median(tensor_x, dim=n):按照第n维计算tensor x的中位数
torch.mode(tensor_x):计算众数
torch.std(tensor_x):计算tensor x的标准差
torch.var(tensor_x):计算方差

In [52]:
x = torch.arange(0, 10, .5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])

In [53]:
torch.mean(x)

tensor(4.7500)

In [54]:
x = torch.randn(4, 5)
x

tensor([[ 0.6701, -1.4694,  0.9754, -0.5541, -1.6590],
        [-1.1974, -1.4447,  0.1833, -0.5690,  0.0999],
        [-0.1914,  0.7106,  0.7853, -2.1468, -1.8539],
        [-0.2284,  0.6631,  0.4335, -2.0939,  0.7917]])

In [55]:
torch.mean(x)

tensor(-0.4047)

In [56]:
torch.mean(x, dim=0)

tensor([-0.2368, -0.3851,  0.5944, -1.3409, -0.6553])

In [57]:
torch.mean(x, dim=1)

tensor([-0.4074, -0.5856, -0.5392, -0.0868])

In [58]:
torch.median(x, dim=0)

torch.return_types.median(
values=tensor([-0.2284, -1.4447,  0.4335, -2.0939, -1.6590]),
indices=tensor([3, 1, 3, 3, 0]))

In [59]:
torch.median(x, dim=1)

torch.return_types.median(
values=tensor([-0.5541, -0.5690, -0.1914,  0.4335]),
indices=tensor([3, 3, 0, 2]))

In [60]:
torch.mode(x)

torch.return_types.mode(
values=tensor([-1.6590, -1.4447, -2.1468, -2.0939]),
indices=tensor([4, 1, 3, 3]))

In [61]:
torch.std(x)

tensor(1.0791)

In [62]:
torch.std(x, dim=1)

tensor([1.2030, 0.7372, 1.3919, 1.1888])

In [63]:
torch.var(x)

tensor(1.1645)

In [65]:
def forward(x):
    return x * w
x = [11.0, 22.0, 33.0]
y = [21.0, 14.0, 64.0]
w = Variable(torch.Tensor([1.0]), requires_grad=True)
print('predict (before training)', 4, forward(4).data[0])

predict (before training) 4 tensor(4.)


In [66]:
def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) * (y_pred - y)

In [68]:
for epoch in range(10):
    for x_val, y_val in zip(x, y):
        l = loss(x_val, y_val)
        l.backward()
        print('\tgrad: ', x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data
        w.grad.data.zero_()
    print('progress: ', epoch, l.data[0])

	grad:  11.0 21.0 tensor(-5.6076e+26)
	grad:  22.0 14.0 tensor(3.1851e+27)
	grad:  33.0 64.0 tensor(-6.2205e+28)
progress:  0 tensor(inf)
	grad:  11.0 21.0 tensor(1.4362e+29)
	grad:  22.0 14.0 tensor(-8.1578e+29)
	grad:  33.0 64.0 tensor(1.5932e+31)
progress:  1 tensor(inf)
	grad:  11.0 21.0 tensor(-3.6786e+31)
	grad:  22.0 14.0 tensor(2.0894e+32)
	grad:  33.0 64.0 tensor(-4.0807e+33)
progress:  2 tensor(inf)
	grad:  11.0 21.0 tensor(9.4218e+33)
	grad:  22.0 14.0 tensor(-5.3516e+34)
	grad:  33.0 64.0 tensor(1.0452e+36)
progress:  3 tensor(inf)
	grad:  11.0 21.0 tensor(-2.4132e+36)
	grad:  22.0 14.0 tensor(1.3707e+37)
	grad:  33.0 64.0 tensor(-2.6769e+38)
progress:  4 tensor(inf)
	grad:  11.0 21.0 tensor(inf)
	grad:  22.0 14.0 tensor(-inf)
	grad:  33.0 64.0 tensor(nan)
progress:  5 tensor(nan)
	grad:  11.0 21.0 tensor(nan)
	grad:  22.0 14.0 tensor(nan)
	grad:  33.0 64.0 tensor(nan)
progress:  6 tensor(nan)
	grad:  11.0 21.0 tensor(nan)
	grad:  22.0 14.0 tensor(nan)
	grad:  33.0 64.0 ten

In [69]:
print('predict (after training)', 4, forward(4).data[0])

predict (after training) 4 tensor(nan)


In [71]:
x = Variable(torch.Tensor(4, 4).uniform_(-4, 5))
y = Variable(torch.Tensor(4, 4).uniform_(-3, 2))
z = torch.mm(x, y)  # 矩阵乘法
print(z.size())

torch.Size([4, 4])


In [72]:
z

tensor([[  2.6788,   6.4665,   4.1274,  -0.7778],
        [ -0.6327,   0.4286,  -4.5341,   2.4343],
        [-13.5663,  -9.1436,   4.3970, -12.1938],
        [-13.6189, -12.8680,  -3.9475,  -2.6551]])

In [73]:
x

tensor([[ 3.2520, -0.5175,  2.7710, -2.6488],
        [-2.6487, -0.9322,  0.8197, -0.8734],
        [ 3.5343,  2.1066,  1.9073,  3.3834],
        [-3.5153,  2.6797, -2.0053,  4.5047]])

这节主要学习了一些pytorch中随机变量的操作，如采样、计算方差、均值等统计量，同时学习了怎么创建变量和自动求导（梯度）